find_package(PkgConfig REQUIRED)
PKG_CHECK_MODULES(PC_LIBFREESRP libfreesrp)

find_path(LIBFREESRP_INCLUDE_DIRS NAMES freesrp.hpp
    HINTS ${PC_LIBFREESRP_INCLUDE_DIRS}
    PATHS
    /usr/include
    /usr/local/include )

find_library(LIBFREESRP_LIBRARIES NAMES freesrp
    HINTS ${PC_LIBFREESRP_LIBRARY_DIRS}
    PATHS
    /usr/lib
    /usr/local/lib )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBFREESRP DEFAULT_MSG LIBFREESRP_LIBRARIES LIBFREESRP_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBFREESRP_LIBRARIES LIBFREESRP_INCLUDE_DIRS)
