INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBOSMOSDR libosmosdr)

find_path(LIBOSMOSDR_INCLUDE_DIRS NAMES osmosdr.h
    HINTS ${PC_LIBOSMOSDR_INCLUDE_DIRS}
    PATHS
    /usr/include
    /usr/local/include )

find_library(LIBOSMOSDR_LIBRARIES NAMES osmosdr
    HINTS ${PC_LIBOSMOSDR_LIBRARY_DIRS}
    PATHS
    /usr/lib
    /usr/local/lib )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBOSMOSDR DEFAULT_MSG LIBOSMOSDR_LIBRARIES LIBOSMOSDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBOSMOSDR_LIBRARIES LIBOSMOSDR_INCLUDE_DIRS)
