INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBBLADERF libbladeRF)

find_path(LIBBLADERF_INCLUDE_DIRS NAMES libbladeRF.h
    HINTS ${PC_LIBBLADERF_INCLUDE_DIRS}
    PATHS
    /usr/include
    /usr/local/include )

find_library(LIBBLADERF_LIBRARIES NAMES bladeRF
    HINTS ${PC_LIBBLADERF_LIBRARY_DIRS}
    PATHS
    /usr/lib
    /usr/local/lib )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBBLADERF DEFAULT_MSG LIBBLADERF_LIBRARIES LIBBLADERF_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBBLADERF_LIBRARIES LIBBLADERF_INCLUDE_DIRS)
