INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBRTLSDR librtlsdr)

find_path(LIBRTLSDR_INCLUDE_DIRS NAMES rtl-sdr.h
    HINTS ${PC_LIBRTLSDR_INCLUDE_DIRS}
    PATHS
    /usr/include
    /usr/local/include )

find_library(LIBRTLSDR_LIBRARIES NAMES rtlsdr
    HINTS ${PC_LIBRTLSDR_LIBRARY_DIRS}
    PATHS
    /usr/lib
    /usr/local/lib )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBRTLSDR DEFAULT_MSG LIBRTLSDR_LIBRARIES LIBRTLSDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBRTLSDR_LIBRARIES LIBRTLSDR_INCLUDE_DIRS)
