INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBMIRISDR libmirisdr)

find_path(LIBMIRISDR_INCLUDE_DIRS NAMES mirisdr.h
    HINTS ${PC_LIBMIRISDR_INCLUDE_DIRS}
    PATHS
    /usr/include
    /usr/local/include )

find_library(LIBMIRISDR_LIBRARIES NAMES mirisdr
    HINTS ${PC_LIBMIRISDR_LIBRARY_DIRS}
    PATHS
    /usr/lib
    /usr/local/lib )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBMIRISDR DEFAULT_MSG LIBMIRISDR_LIBRARIES LIBMIRISDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBMIRISDR_LIBRARIES LIBMIRISDR_INCLUDE_DIRS)
