find_package(PkgConfig REQUIRED)
PKG_CHECK_MODULES(PC_GNURADIO_FCDPP gnuradio-fcdproplus)

FIND_PATH(
    GNURADIO_FCDPP_INCLUDE_DIRS
    NAMES fcdproplus/api.h
    HINTS $ENV{GNURADIO_FCDPP_DIR}/include
        ${PC_GNURADIO_FCDPP_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_FCDPP_LIBRARIES
    NAMES gnuradio-fcdproplus
    HINTS $ENV{GNURADIO_FCDPP_DIR}/lib
        ${PC_GNURADIO_FCDPP_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_FCDPP DEFAULT_MSG GNURADIO_FCDPP_LIBRARIES GNURADIO_FCDPP_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_FCDPP_LIBRARIES GNURADIO_FCDPP_INCLUDE_DIRS)
