find_package(PkgConfig REQUIRED)
PKG_CHECK_MODULES(PC_LIBSDRPLAY libsdrplay)

find_path(LIBSDRPLAY_INCLUDE_DIRS NAMES mirsdrapi-rsp.h
    HINTS ${PC_LIBSDRPLAY_INCLUDE_DIRS}
    PATHS
    /usr/include
    /usr/local/include )

find_library(LIBSDRPLAY_LIBRARIES NAMES mirsdrapi-rsp
    HINTS ${PC_LIBSDRPLAY_LIBRARY_DIRS}
    PATHS
    /usr/lib
    /usr/local/lib )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBSDRPLAY DEFAULT_MSG LIBSDRPLAY_LIBRARIES LIBSDRPLAY_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBSDRPLAY_LIBRARIES LIBSDRPLAY_INCLUDE_DIRS)
